# Generated by Django 4.2.1 on 2023-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('articl', models.IntegerField()),
                ('image', models.URLField(default='D', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='my_product',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
